import {
  User,
  Sauna,
  CheckIn,
  Collection,
  CollectionItemMeta,
  CollectionItemType,
  SaunaReview,
  Quest,
  CommunityPost,
  ChatMessage,
} from "./types";

// ─── Current User ────────────────────────────────────────────────────────────

export const currentUser: User = {
  id: "user-1",
  nickname: "열탕러버",
  email: "sauna@example.com",
  level: 7,
  xp: 1720,
  title: "Hot Stone Master",
  profileImgUrl: "https://picsum.photos/seed/user1/100/100",
  createdAt: "2024-06-01T09:00:00Z",
};

// ─── Saunas ──────────────────────────────────────────────────────────────────

export const saunas: Sauna[] = [
  // Seoul (10)
  {
    id: "seoul-1",
    name: "용산 드래곤 사우나",
    address: "서울특별시 용산구 이태원로 123",
    region: "seoul",
    category: "finnish",
    locationLat: 37.5344,
    locationLng: 126.9947,
    description: "용산 중심부에 위치한 정통 핀란드식 사우나. 북유럽 감성과 최고급 시설을 자랑합니다.",
    imageUrl: "https://picsum.photos/seed/seoul-1/400/300",
    totalConqueredCount: 312,
  },
  {
    id: "seoul-2",
    name: "강남 포레스트 스파",
    address: "서울특별시 강남구 테헤란로 456",
    region: "seoul",
    category: "hotel",
    locationLat: 37.5065,
    locationLng: 127.0536,
    description: "강남 테헤란로 한복판, 도심 속 숲을 테마로 한 프리미엄 호텔 스파.",
    imageUrl: "https://picsum.photos/seed/seoul-2/400/300",
    totalConqueredCount: 487,
  },
  {
    id: "seoul-3",
    name: "종로 전통 찜질방",
    address: "서울특별시 종로구 종로 789",
    region: "seoul",
    category: "jjimjilbang",
    locationLat: 37.5700,
    locationLng: 126.9820,
    description: "조선시대 한옥 건물을 개조한 전통 찜질방. 황토방과 옥돌방이 인기입니다.",
    imageUrl: "https://picsum.photos/seed/seoul-3/400/300",
    totalConqueredCount: 628,
  },
  {
    id: "seoul-4",
    name: "마포 하늘 사우나",
    address: "서울특별시 마포구 홍익로 210",
    region: "seoul",
    category: "bulgama",
    locationLat: 37.5499,
    locationLng: 126.9086,
    description: "한강 조망이 가능한 루프탑 불가마 사우나. 저녁 야경이 특히 아름답습니다.",
    imageUrl: "https://picsum.photos/seed/seoul-4/400/300",
    totalConqueredCount: 215,
  },
  {
    id: "seoul-5",
    name: "성동 리버뷰 스파",
    address: "서울특별시 성동구 왕십리로 55",
    region: "seoul",
    category: "finnish",
    locationLat: 37.5633,
    locationLng: 127.0372,
    description: "청계천 옆에 자리한 리버뷰 스파. 핀란드산 자작나무로 지어진 사우나실이 일품.",
    imageUrl: "https://picsum.photos/seed/seoul-5/400/300",
    totalConqueredCount: 178,
  },
  {
    id: "seoul-6",
    name: "송파 올림픽 사우나",
    address: "서울특별시 송파구 올림픽로 300",
    region: "seoul",
    category: "jjimjilbang",
    locationLat: 37.5140,
    locationLng: 127.1144,
    description: "올림픽공원 인근 대형 찜질방. 가족 단위 방문객에게 인기가 높습니다.",
    imageUrl: "https://picsum.photos/seed/seoul-6/400/300",
    totalConqueredCount: 534,
  },
  {
    id: "seoul-7",
    name: "영등포 시티 스파",
    address: "서울특별시 영등포구 여의대방로 88",
    region: "seoul",
    category: "hotel",
    locationLat: 37.5261,
    locationLng: 126.8962,
    description: "여의도 비즈니스 중심가의 도심형 스파. 직장인들의 퇴근 후 힐링 스폿.",
    imageUrl: "https://picsum.photos/seed/seoul-7/400/300",
    totalConqueredCount: 290,
  },
  {
    id: "seoul-8",
    name: "서초 그린힐 사우나",
    address: "서울특별시 서초구 서초대로 501",
    region: "seoul",
    category: "bulgama",
    locationLat: 37.4837,
    locationLng: 127.0324,
    description: "우면산 자락에 위치한 그린힐 불가마. 편백나무 향이 가득한 힐링 공간.",
    imageUrl: "https://picsum.photos/seed/seoul-8/400/300",
    totalConqueredCount: 167,
  },
  {
    id: "seoul-9",
    name: "동작 노을 찜질방",
    address: "서울특별시 동작구 노량진로 44",
    region: "seoul",
    category: "jjimjilbang",
    locationLat: 37.5119,
    locationLng: 126.9398,
    description: "한강이 내려다보이는 노을 찜질방. 낙조를 바라보며 즐기는 찜질이 압권.",
    imageUrl: "https://picsum.photos/seed/seoul-9/400/300",
    totalConqueredCount: 342,
  },
  {
    id: "seoul-10",
    name: "관악 마운틴 스파",
    address: "서울특별시 관악구 관악로 1700",
    region: "seoul",
    category: "finnish",
    locationLat: 37.4783,
    locationLng: 126.9516,
    description: "관악산 등산로 입구에 위치한 등산객 전용 스파. 등산 후 피로 해소에 최적.",
    imageUrl: "https://picsum.photos/seed/seoul-10/400/300",
    totalConqueredCount: 423,
  },

  // Gyeonggi (8)
  {
    id: "gyeonggi-1",
    name: "수원 캐슬 스파",
    address: "경기도 수원시 팔달구 화서문로 12",
    region: "gyeonggi",
    category: "hotel",
    locationLat: 37.2886,
    locationLng: 126.9968,
    description: "수원화성 옆에 자리한 성곽 테마 호텔 스파. 역사와 현대가 공존하는 특별한 경험.",
    imageUrl: "https://picsum.photos/seed/gyeonggi-1/400/300",
    totalConqueredCount: 389,
  },
  {
    id: "gyeonggi-2",
    name: "성남 판교 사우나",
    address: "경기도 성남시 분당구 판교역로 146",
    region: "gyeonggi",
    category: "finnish",
    locationLat: 37.3946,
    locationLng: 127.1112,
    description: "판교 IT 밸리 내 첨단 시설의 핀란드 사우나. 테크 기업 직원들에게 인기.",
    imageUrl: "https://picsum.photos/seed/gyeonggi-2/400/300",
    totalConqueredCount: 256,
  },
  {
    id: "gyeonggi-3",
    name: "고양 스타필드 스파",
    address: "경기도 고양시 덕양구 고양대로 1955",
    region: "gyeonggi",
    category: "jjimjilbang",
    locationLat: 37.6574,
    locationLng: 126.8305,
    description: "스타필드 고양 내 대형 찜질방. 쇼핑과 찜질을 한 번에 즐길 수 있습니다.",
    imageUrl: "https://picsum.photos/seed/gyeonggi-3/400/300",
    totalConqueredCount: 612,
  },
  {
    id: "gyeonggi-4",
    name: "용인 에버그린 사우나",
    address: "경기도 용인시 기흥구 에버랜드로 199",
    region: "gyeonggi",
    category: "bulgama",
    locationLat: 37.2941,
    locationLng: 127.2037,
    description: "에버랜드 인근 자연 속 불가마 사우나. 가족 여행 코스로 인기 높은 스폿.",
    imageUrl: "https://picsum.photos/seed/gyeonggi-4/400/300",
    totalConqueredCount: 445,
  },
  {
    id: "gyeonggi-5",
    name: "파주 힐링 스파",
    address: "경기도 파주시 탄현면 헤이리마을길 93",
    region: "gyeonggi",
    category: "finnish",
    locationLat: 37.7628,
    locationLng: 126.7285,
    description: "헤이리 예술마을 옆 자연친화적 힐링 스파. 예술 감성과 웰니스의 만남.",
    imageUrl: "https://picsum.photos/seed/gyeonggi-5/400/300",
    totalConqueredCount: 198,
  },
  {
    id: "gyeonggi-6",
    name: "안양 시그니처 사우나",
    address: "경기도 안양시 만안구 안양로 123",
    region: "gyeonggi",
    category: "hotel",
    locationLat: 37.3943,
    locationLng: 126.9568,
    description: "안양 중심가 프리미엄 호텔 내 시그니처 사우나. 고급스러운 인테리어가 특징.",
    imageUrl: "https://picsum.photos/seed/gyeonggi-6/400/300",
    totalConqueredCount: 231,
  },
  {
    id: "gyeonggi-7",
    name: "화성 동탄 스파",
    address: "경기도 화성시 동탄대로 537",
    region: "gyeonggi",
    category: "jjimjilbang",
    locationLat: 37.2002,
    locationLng: 127.0728,
    description: "동탄 신도시 최대 규모 찜질방. 다양한 테마의 찜질실과 수영장 구비.",
    imageUrl: "https://picsum.photos/seed/gyeonggi-7/400/300",
    totalConqueredCount: 503,
  },
  {
    id: "gyeonggi-8",
    name: "부천 아쿠아 사우나",
    address: "경기도 부천시 원미구 길주로 210",
    region: "gyeonggi",
    category: "bulgama",
    locationLat: 37.5034,
    locationLng: 126.7660,
    description: "수치료와 불가마를 결합한 아쿠아 사우나. 다양한 수온의 풀이 준비되어 있습니다.",
    imageUrl: "https://picsum.photos/seed/gyeonggi-8/400/300",
    totalConqueredCount: 317,
  },

  // Jeju (5)
  {
    id: "jeju-1",
    name: "제주 오션뷰 스파",
    address: "제주특별자치도 제주시 연북로 100",
    region: "jeju",
    category: "hotel",
    locationLat: 33.5141,
    locationLng: 126.5219,
    description: "제주 바다가 한눈에 보이는 오션뷰 스파. 제주 화산석으로 지어진 사우나실이 명물.",
    imageUrl: "https://picsum.photos/seed/jeju-1/400/300",
    totalConqueredCount: 741,
  },
  {
    id: "jeju-2",
    name: "서귀포 한라 사우나",
    address: "제주특별자치도 서귀포시 중문관광로 72",
    region: "jeju",
    category: "finnish",
    locationLat: 33.2541,
    locationLng: 126.4124,
    description: "한라산을 바라보며 즐기는 핀란드 사우나. 제주 감귤 아로마 어우시가 특별합니다.",
    imageUrl: "https://picsum.photos/seed/jeju-2/400/300",
    totalConqueredCount: 589,
  },
  {
    id: "jeju-3",
    name: "제주 돌하르방 찜질방",
    address: "제주특별자치도 제주시 노형로 481",
    region: "jeju",
    category: "jjimjilbang",
    locationLat: 33.4891,
    locationLng: 126.4785,
    description: "제주 전통 문화를 테마로 한 찜질방. 현무암 황토방과 용암 사우나가 인기.",
    imageUrl: "https://picsum.photos/seed/jeju-3/400/300",
    totalConqueredCount: 456,
  },
  {
    id: "jeju-4",
    name: "애월 바다 스파",
    address: "제주특별자치도 제주시 애월읍 애월해안로 650",
    region: "jeju",
    category: "bulgama",
    locationLat: 33.4632,
    locationLng: 126.3103,
    description: "에메랄드 바다 앞 노천 스파. 일몰과 함께 즐기는 불가마가 최고의 경험.",
    imageUrl: "https://picsum.photos/seed/jeju-4/400/300",
    totalConqueredCount: 678,
  },
  {
    id: "jeju-5",
    name: "성산 일출 사우나",
    address: "제주특별자치도 서귀포시 성산읍 일출로 284",
    region: "jeju",
    category: "finnish",
    locationLat: 33.4581,
    locationLng: 126.9427,
    description: "성산일출봉 앞 일출 명소 사우나. 해가 뜰 때 즐기는 새벽 사우나가 압권.",
    imageUrl: "https://picsum.photos/seed/jeju-5/400/300",
    totalConqueredCount: 523,
  },
];

// ─── Check-ins ────────────────────────────────────────────────────────────────

export const checkIns: CheckIn[] = [
  {
    id: "checkin-1",
    userId: "user-1",
    saunaId: "seoul-1",
    ratingHotTub: 5,
    ratingColdTub: 4,
    ratingSauna: 5,
    ratingCleanliness: 5,
    ratingFacility: 4,
    ratingOverall: 5,
    oneLineReview: "핀란드에 온 줄 알았어요. 정말 최고의 사우나!",
    privateNote: "다음엔 아우프구스 타임에 맞춰 가야겠다.",
    visitedAt: "2025-11-15T14:00:00Z",
    createdAt: "2025-11-15T16:30:00Z",
  },
  {
    id: "checkin-2",
    userId: "user-1",
    saunaId: "seoul-2",
    ratingHotTub: 4,
    ratingColdTub: 4,
    ratingSauna: 4,
    ratingCleanliness: 5,
    ratingFacility: 5,
    ratingOverall: 4,
    oneLineReview: "강남 한복판에서 즐기는 숲 테마 스파. 분위기 최고.",
    privateNote: "주말 예약 필수. 평일이 훨씬 여유롭다.",
    visitedAt: "2025-12-03T11:00:00Z",
    createdAt: "2025-12-03T13:00:00Z",
  },
  {
    id: "checkin-3",
    userId: "user-1",
    saunaId: "seoul-3",
    ratingHotTub: 4,
    ratingColdTub: 3,
    ratingSauna: 4,
    ratingCleanliness: 4,
    ratingFacility: 3,
    ratingOverall: 4,
    oneLineReview: "황토방이 정말 좋았어요. 옛날 감성 물씬.",
    privateNote: "황토방 30분이 적당. 너무 오래 있으면 어지러움.",
    visitedAt: "2026-01-10T15:00:00Z",
    createdAt: "2026-01-10T17:00:00Z",
  },
  {
    id: "checkin-4",
    userId: "user-1",
    saunaId: "gyeonggi-1",
    ratingHotTub: 5,
    ratingColdTub: 4,
    ratingSauna: 5,
    ratingCleanliness: 5,
    ratingFacility: 5,
    ratingOverall: 5,
    oneLineReview: "수원화성 야경 보며 즐기는 스파. 역사 덕후 강추!",
    privateNote: "화성 구경하고 저녁에 방문하면 더 좋을 듯.",
    visitedAt: "2026-01-25T18:00:00Z",
    createdAt: "2026-01-25T20:00:00Z",
  },
  {
    id: "checkin-5",
    userId: "user-1",
    saunaId: "gyeonggi-2",
    ratingHotTub: 3,
    ratingColdTub: 4,
    ratingSauna: 5,
    ratingCleanliness: 5,
    ratingFacility: 5,
    ratingOverall: 4,
    oneLineReview: "판교 직장인들이 사랑하는 사우나. 시설이 정말 현대적.",
    privateNote: "평일 저녁 퇴근 시간에는 매우 붐빔. 오전 방문 추천.",
    visitedAt: "2026-02-08T19:00:00Z",
    createdAt: "2026-02-08T21:00:00Z",
  },
  {
    id: "checkin-6",
    userId: "user-1",
    saunaId: "jeju-1",
    ratingHotTub: 5,
    ratingColdTub: 5,
    ratingSauna: 5,
    ratingCleanliness: 5,
    ratingFacility: 5,
    ratingOverall: 5,
    oneLineReview: "바다를 보며 사우나를… 이건 진짜 천국입니다.",
    privateNote: "제주 여행 필수 코스로 등록! 일출 전 새벽 방문 도전해보고 싶다.",
    visitedAt: "2026-03-01T10:00:00Z",
    createdAt: "2026-03-01T12:30:00Z",
  },
];

// ─── Collection Items Meta ────────────────────────────────────────────────────

export const COLLECTION_ITEMS_META: CollectionItemMeta[] = [
  { itemType: "wooden_bucket", displayName: "나무 양동이", emoji: "🪣", rarity: "common" },
  { itemType: "towel_set", displayName: "타월 세트", emoji: "🧖", rarity: "common" },
  { itemType: "sand_timer", displayName: "모래시계", emoji: "⏳", rarity: "common" },
  { itemType: "steam_stone", displayName: "스팀 스톤", emoji: "🪨", rarity: "common" },
  { itemType: "scented_oil", displayName: "아로마 오일", emoji: "🧴", rarity: "rare" },
  { itemType: "sauna_hat", displayName: "사우나 모자", emoji: "👒", rarity: "rare" },
  { itemType: "thermometer", displayName: "온도계", emoji: "🌡️", rarity: "rare" },
  { itemType: "birch_whisk", displayName: "자작나무 위스크", emoji: "🌿", rarity: "rare" },
  { itemType: "ice_bucket", displayName: "아이스 버킷", emoji: "🧊", rarity: "rare" },
  { itemType: "luxury_robe", displayName: "럭셔리 로브", emoji: "👘", rarity: "legendary" },
];

// ─── Collections ──────────────────────────────────────────────────────────────

export const collections: Collection[] = [
  // Unlocked (5)
  { id: "col-1", userId: "user-1", itemType: "wooden_bucket", unlockedAt: "2024-08-10T10:00:00Z" },
  { id: "col-2", userId: "user-1", itemType: "towel_set", unlockedAt: "2024-10-22T14:00:00Z" },
  { id: "col-3", userId: "user-1", itemType: "scented_oil", unlockedAt: "2025-01-05T09:00:00Z" },
  { id: "col-4", userId: "user-1", itemType: "sauna_hat", unlockedAt: "2025-05-17T11:00:00Z" },
  { id: "col-5", userId: "user-1", itemType: "sand_timer", unlockedAt: "2025-09-30T16:00:00Z" },
  // Locked (5)
  { id: "col-6", userId: "user-1", itemType: "steam_stone", unlockedAt: null },
  { id: "col-7", userId: "user-1", itemType: "thermometer", unlockedAt: null },
  { id: "col-8", userId: "user-1", itemType: "birch_whisk", unlockedAt: null },
  { id: "col-9", userId: "user-1", itemType: "ice_bucket", unlockedAt: null },
  { id: "col-10", userId: "user-1", itemType: "luxury_robe", unlockedAt: null },
];

// ─── Quests ───────────────────────────────────────────────────────────────────

export const quests: Quest[] = [
  {
    id: "quest-1",
    title: "전통 사우나 탐험",
    description: "전통 찜질방 또는 불가마 사우나를 3곳 방문하세요.",
    icon: "🏛️",
    current: 2,
    target: 3,
    xpReward: 200,
  },
  {
    id: "quest-2",
    title: "주간 탐험가",
    description: "한 주 안에 5곳의 서로 다른 사우나를 방문하세요.",
    icon: "🧭",
    current: 1,
    target: 5,
    xpReward: 300,
  },
  {
    id: "quest-3",
    title: "열기 공유하기",
    description: "커뮤니티 모임을 주최하세요.",
    icon: "🔥",
    current: 0,
    target: 1,
    xpReward: 100,
  },
];

// ─── Community Posts ──────────────────────────────────────────────────────────

export const communityPosts: CommunityPost[] = [
  {
    id: "post-1",
    hostId: "user-2",
    hostNickname: "사우나킹",
    hostTitle: "Steam Veteran",
    saunaId: "seoul-1",
    saunaName: "용산 드래곤 사우나",
    region: "seoul",
    category: "finnish",
    maxSpots: 6,
    currentSpots: 4,
    meetDate: "2026-04-05T15:00:00Z",
    description: "용산 드래곤 사우나에서 같이 아우프구스 체험해요! 초보자 환영합니다 :)",
    createdAt: "2026-03-20T10:00:00Z",
    status: "recruiting",
  },
  {
    id: "post-2",
    hostId: "user-3",
    hostNickname: "제주여행자",
    hostTitle: "Heat Seeker",
    saunaId: "jeju-4",
    saunaName: "애월 바다 스파",
    region: "jeju",
    category: "bulgama",
    maxSpots: 4,
    currentSpots: 2,
    meetDate: "2026-04-12T17:00:00Z",
    description: "애월 노을 보면서 불가마 같이 즐겨요~ 제주 한 달 살기 중인 분들 특히 환영!",
    createdAt: "2026-03-21T09:30:00Z",
    status: "recruiting",
  },
  {
    id: "post-3",
    hostId: "user-4",
    hostNickname: "판교개발자",
    hostTitle: "Sauna Regular",
    saunaId: "gyeonggi-2",
    saunaName: "성남 판교 사우나",
    region: "gyeonggi",
    category: "finnish",
    maxSpots: 5,
    currentSpots: 5,
    meetDate: "2026-03-28T20:00:00Z",
    description: "퇴근 후 판교 사우나 모임. 개발자/직장인 모여요! 자리 마감 임박.",
    createdAt: "2026-03-18T18:00:00Z",
    status: "confirmed",
  },
  {
    id: "post-4",
    hostId: "user-5",
    hostNickname: "찜질방마스터",
    hostTitle: "Bath Explorer",
    saunaId: "seoul-3",
    saunaName: "종로 전통 찜질방",
    region: "seoul",
    category: "jjimjilbang",
    maxSpots: 8,
    currentSpots: 3,
    meetDate: "2026-04-19T13:00:00Z",
    description: "종로 전통 찜질방에서 황토방 투어! 옛날 감성 좋아하시는 분들 함께해요.",
    createdAt: "2026-03-22T14:00:00Z",
    status: "recruiting",
  },
  {
    id: "post-5",
    hostId: "user-6",
    hostNickname: "웰니스워커",
    hostTitle: "Warm Beginner",
    saunaId: "jeju-5",
    saunaName: "성산 일출 사우나",
    region: "jeju",
    category: "finnish",
    maxSpots: 4,
    currentSpots: 1,
    meetDate: "2026-04-25T05:30:00Z",
    description: "성산일출봉 일출 보고 사우나! 새벽 4시 반 집결. 인생 경험 원하는 분 오세요.",
    createdAt: "2026-03-23T08:00:00Z",
    status: "completed",
  },
];

// ─── Chat Messages ────────────────────────────────────────────────────────────

export const chatMessages: ChatMessage[] = [
  // post-1 messages
  { id: "msg-1-1", postId: "post-1", userId: "user-2", nickname: "사우나킹", message: "안녕하세요! 4월 5일 용산 드래곤에서 아우프구스 체험 모임입니다 🔥", timestamp: "2026-03-20T10:05:00Z", isSystem: false },
  { id: "msg-1-2", postId: "post-1", userId: "user-1", nickname: "열탕러버", message: "오 저도 참여하고 싶어요! 초보인데 괜찮을까요?", timestamp: "2026-03-20T11:30:00Z", isSystem: false },
  { id: "msg-1-3", postId: "post-1", userId: "user-2", nickname: "사우나킹", message: "물론이죠! 초보자분들도 많이 오세요 ㅎㅎ 수건이랑 물만 챙겨오시면 됩니다", timestamp: "2026-03-20T11:45:00Z", isSystem: false },
  { id: "msg-1-4", postId: "post-1", userId: "user-7", nickname: "핀란드매니아", message: "저도 참여할게요! 타올 세트 여분으로 가져갈게요", timestamp: "2026-03-21T09:00:00Z", isSystem: false },
  // post-3 messages (confirmed)
  { id: "msg-3-1", postId: "post-3", userId: "user-4", nickname: "판교개발자", message: "금요일 퇴근 후 8시에 판교 사우나 앞에서 만나요!", timestamp: "2026-03-18T18:30:00Z", isSystem: false },
  { id: "msg-3-2", postId: "post-3", userId: "user-8", nickname: "코딩하는사우너", message: "넵! 저 포함 5명 다 모인거죠?", timestamp: "2026-03-19T10:00:00Z", isSystem: false },
  { id: "msg-3-3", postId: "post-3", userId: "user-4", nickname: "판교개발자", message: "네 맞습니다! 인원 확정이요~", timestamp: "2026-03-19T10:15:00Z", isSystem: false },
  { id: "msg-3-4", postId: "post-3", userId: "system", nickname: "시스템", message: "🎉 모임이 확정되었습니다! 3월 28일 20:00 성남 판교 사우나에서 만나요.", timestamp: "2026-03-19T10:16:00Z", isSystem: true },
  { id: "msg-3-5", postId: "post-3", userId: "user-4", nickname: "판교개발자", message: "다들 늦지 않게 와주세요! 사물함 번호는 당일 공유할게요", timestamp: "2026-03-20T15:00:00Z", isSystem: false },
  // post-5 messages (completed)
  { id: "msg-5-1", postId: "post-5", userId: "user-6", nickname: "웰니스워커", message: "새벽 4시 반 성산일출봉 주차장 집합입니다!", timestamp: "2026-03-23T08:30:00Z", isSystem: false },
  { id: "msg-5-2", postId: "post-5", userId: "user-1", nickname: "열탕러버", message: "일출 보고 사우나라니... 인생 버킷리스트예요 🌅", timestamp: "2026-03-24T20:00:00Z", isSystem: false },
  { id: "msg-5-3", postId: "post-5", userId: "system", nickname: "시스템", message: "🎉 모임이 확정되었습니다! 4월 25일 05:30 성산 일출 사우나에서 만나요.", timestamp: "2026-03-25T10:00:00Z", isSystem: true },
  { id: "msg-5-4", postId: "post-5", userId: "system", nickname: "시스템", message: "✅ 모임이 완료되었습니다! 체크인을 잊지 마세요.", timestamp: "2026-04-25T10:00:00Z", isSystem: true },
];

// ─── Sauna Reviews ────────────────────────────────────────────────────────────

export const saunaReviews: Record<string, SaunaReview[]> = {
  "seoul-1": [
    { nickname: "열탕러버", title: "Hot Stone Master", ratingOverall: 5, oneLineReview: "핀란드에 온 줄 알았어요. 정말 최고의 사우나!", visitedAt: "2025-11-15" },
    { nickname: "사우나킹", title: "Steam Veteran", ratingOverall: 5, oneLineReview: "아우프구스 이벤트가 정말 대단합니다.", visitedAt: "2025-10-08" },
    { nickname: "힐링러", title: "Bath Explorer", ratingOverall: 4, oneLineReview: "시설은 훌륭한데 가격이 조금 비쌈.", visitedAt: "2025-09-20" },
  ],
  "seoul-2": [
    { nickname: "강남러버", title: "Heat Seeker", ratingOverall: 4, oneLineReview: "도심 속 숲 느낌이 정말 좋아요.", visitedAt: "2025-12-01" },
    { nickname: "스파퀸", title: "Sauna Regular", ratingOverall: 5, oneLineReview: "프리미엄 서비스, 가격도 합리적.", visitedAt: "2025-11-20" },
    { nickname: "주말탐험가", title: "Warm Beginner", ratingOverall: 3, oneLineReview: "주말엔 너무 붐벼요.", visitedAt: "2025-10-30" },
  ],
  "seoul-3": [
    { nickname: "전통파", title: "Bath Explorer", ratingOverall: 5, oneLineReview: "황토방이 진짜 명불허전!", visitedAt: "2026-01-08" },
    { nickname: "종로탐방", title: "Newbie Steamer", ratingOverall: 4, oneLineReview: "한옥 분위기가 정말 독특해요.", visitedAt: "2025-12-25" },
    { nickname: "찜질왕", title: "Steam Veteran", ratingOverall: 4, oneLineReview: "옥돌방이 다른 곳보다 훨씬 뜨거워.", visitedAt: "2025-11-11" },
    { nickname: "힐링탐구자", title: "Heat Seeker", ratingOverall: 5, oneLineReview: "가성비 최고의 전통 찜질방.", visitedAt: "2025-10-05" },
  ],
  "seoul-4": [
    { nickname: "한강뷰어", title: "Sauna Regular", ratingOverall: 4, oneLineReview: "루프탑에서 한강 보며 불가마, 환상입니다.", visitedAt: "2025-12-10" },
    { nickname: "야경헌터", title: "Bath Explorer", ratingOverall: 5, oneLineReview: "저녁 야경과 불가마의 조합. 완벽.", visitedAt: "2025-11-28" },
  ],
  "seoul-5": [
    { nickname: "청계천워커", title: "Heat Seeker", ratingOverall: 4, oneLineReview: "청계천 옆 자작나무 향이 너무 좋아요.", visitedAt: "2026-01-15" },
    { nickname: "핀란드팬", title: "Steam Veteran", ratingOverall: 5, oneLineReview: "정통 핀란드 방식 고집하는 게 느껴져요.", visitedAt: "2025-12-20" },
  ],
  "seoul-6": [
    { nickname: "가족나들이", title: "Sauna Regular", ratingOverall: 4, oneLineReview: "아이들이랑 오기 딱 좋아요.", visitedAt: "2026-01-20" },
    { nickname: "올림픽러버", title: "Warm Beginner", ratingOverall: 4, oneLineReview: "넓고 쾌적해요. 가족 추천 코스.", visitedAt: "2025-12-15" },
    { nickname: "주말가족", title: "Newbie Steamer", ratingOverall: 3, oneLineReview: "주말엔 아이들이 너무 많아서 시끄러움.", visitedAt: "2025-11-30" },
  ],
  "seoul-7": [
    { nickname: "여의도직장인", title: "Bath Explorer", ratingOverall: 4, oneLineReview: "퇴근 후 스트레스 해소에 최고.", visitedAt: "2026-02-01" },
    { nickname: "비즈니스맨", title: "Heat Seeker", ratingOverall: 5, oneLineReview: "위치가 최고. 회의 후 바로 갈 수 있어요.", visitedAt: "2026-01-25" },
  ],
  "seoul-8": [
    { nickname: "편백나무좋아", title: "Sauna Regular", ratingOverall: 5, oneLineReview: "편백나무 향이 진짜 힐링 그 자체.", visitedAt: "2026-02-10" },
    { nickname: "서초힐러", title: "Steam Veteran", ratingOverall: 4, oneLineReview: "산 속 분위기가 도심에서 느끼기 드문 경험.", visitedAt: "2025-12-22" },
  ],
  "seoul-9": [
    { nickname: "노을감성", title: "Warm Beginner", ratingOverall: 5, oneLineReview: "한강 노을 보며 찜질방이 이렇게 좋을 줄이야.", visitedAt: "2026-01-30" },
    { nickname: "동작구민", title: "Bath Explorer", ratingOverall: 4, oneLineReview: "동네 찜질방인데 경치가 최고예요.", visitedAt: "2025-11-05" },
  ],
  "seoul-10": [
    { nickname: "관악산러너", title: "Heat Seeker", ratingOverall: 5, oneLineReview: "등산 후 바로 사우나, 이것이 진정한 힐링.", visitedAt: "2026-02-15" },
    { nickname: "등산마니아", title: "Sauna Regular", ratingOverall: 4, oneLineReview: "등산객 특화 서비스가 꼼꼼해요.", visitedAt: "2026-01-12" },
    { nickname: "주말산악회", title: "Bath Explorer", ratingOverall: 5, oneLineReview: "산악회에서 단체로 왔는데 다 만족했어요.", visitedAt: "2025-12-07" },
  ],
  "gyeonggi-1": [
    { nickname: "수원역사인", title: "Bath Explorer", ratingOverall: 5, oneLineReview: "화성 야경 보면서 스파 즐기는 건 여기만 가능.", visitedAt: "2026-01-28" },
    { nickname: "역사덕후", title: "Heat Seeker", ratingOverall: 5, oneLineReview: "역사적 배경과 현대 스파의 완벽한 조화.", visitedAt: "2025-12-18" },
    { nickname: "경기남부러버", title: "Warm Beginner", ratingOverall: 4, oneLineReview: "수원 여행 중 들렀는데 대만족!", visitedAt: "2025-11-22" },
  ],
  "gyeonggi-2": [
    { nickname: "판교개발자", title: "Sauna Regular", ratingOverall: 4, oneLineReview: "퇴근 후 피로 해소에 안성맞춤.", visitedAt: "2026-02-10" },
    { nickname: "IT맨", title: "Steam Veteran", ratingOverall: 5, oneLineReview: "첨단 시설에 핀란드 감성. 판교 직장인 필수.", visitedAt: "2026-01-18" },
  ],
  "gyeonggi-3": [
    { nickname: "쇼핑찜질러", title: "Bath Explorer", ratingOverall: 4, oneLineReview: "쇼핑하다 지쳐서 들어왔는데 살아났어요.", visitedAt: "2026-01-05" },
    { nickname: "고양시민", title: "Sauna Regular", ratingOverall: 4, oneLineReview: "규모가 정말 크고 다양한 시설이 좋아요.", visitedAt: "2025-12-28" },
    { nickname: "가족나들이2", title: "Warm Beginner", ratingOverall: 5, oneLineReview: "스타필드 갔다가 찜질방까지, 완벽한 하루.", visitedAt: "2025-11-15" },
  ],
  "gyeonggi-4": [
    { nickname: "에버랜드팬", title: "Heat Seeker", ratingOverall: 4, oneLineReview: "에버랜드 다음 날 피로 해소로 완벽.", visitedAt: "2026-02-20" },
    { nickname: "용인주민", title: "Bath Explorer", ratingOverall: 5, oneLineReview: "자연 속 불가마는 용인에서만 가능.", visitedAt: "2026-01-08" },
  ],
  "gyeonggi-5": [
    { nickname: "헤이리예술가", title: "Sauna Regular", ratingOverall: 5, oneLineReview: "예술 마을 감성과 사우나의 만남. 독창적.", visitedAt: "2025-12-30" },
    { nickname: "파주여행자", title: "Steam Veteran", ratingOverall: 4, oneLineReview: "분위기가 너무 좋아요. 조용하고 힐링됩니다.", visitedAt: "2025-11-08" },
  ],
  "gyeonggi-6": [
    { nickname: "안양러버", title: "Bath Explorer", ratingOverall: 4, oneLineReview: "인테리어가 정말 고급스러워요.", visitedAt: "2026-02-05" },
    { nickname: "경기서부탐험", title: "Heat Seeker", ratingOverall: 4, oneLineReview: "호텔 스파 퀄리티에 합리적인 가격.", visitedAt: "2026-01-22" },
  ],
  "gyeonggi-7": [
    { nickname: "동탄신도시민", title: "Sauna Regular", ratingOverall: 5, oneLineReview: "동탄 최고의 찜질방! 시설 정말 좋아요.", visitedAt: "2026-02-12" },
    { nickname: "신도시생활자", title: "Warm Beginner", ratingOverall: 4, oneLineReview: "다양한 테마방이 있어서 매번 새로운 느낌.", visitedAt: "2026-01-30" },
    { nickname: "화성탐험가", title: "Bath Explorer", ratingOverall: 4, oneLineReview: "수영장까지 있어서 아이들이 정말 좋아해요.", visitedAt: "2025-12-10" },
  ],
  "gyeonggi-8": [
    { nickname: "아쿠아테라피", title: "Heat Seeker", ratingOverall: 5, oneLineReview: "수치료와 불가마 조합이 최강.", visitedAt: "2026-02-18" },
    { nickname: "부천시민", title: "Steam Veteran", ratingOverall: 4, oneLineReview: "다양한 수온 풀이 있어서 취향껏 즐길 수 있어요.", visitedAt: "2026-01-14" },
  ],
  "jeju-1": [
    { nickname: "제주여행자", title: "Heat Seeker", ratingOverall: 5, oneLineReview: "바다를 보며 사우나를… 이건 진짜 천국입니다.", visitedAt: "2026-03-05" },
    { nickname: "오션뷰마니아", title: "Sauna Regular", ratingOverall: 5, oneLineReview: "제주 왔으면 무조건 여기. 인생 스파.", visitedAt: "2026-02-20" },
    { nickname: "제주살이", title: "Steam Veteran", ratingOverall: 5, oneLineReview: "화산석 사우나실이 정말 특별해요.", visitedAt: "2026-01-30" },
    { nickname: "신혼여행커플", title: "Bath Explorer", ratingOverall: 5, oneLineReview: "커플 패키지가 너무 좋아요!", visitedAt: "2025-12-24" },
  ],
  "jeju-2": [
    { nickname: "한라산등반자", title: "Heat Seeker", ratingOverall: 5, oneLineReview: "한라산 등반 후 여기 오면 천국이 따로 없어요.", visitedAt: "2026-03-10" },
    { nickname: "감귤향러버", title: "Bath Explorer", ratingOverall: 5, oneLineReview: "감귤 아로마 어우시가 다른 사우나와 차별화.", visitedAt: "2026-02-14" },
    { nickname: "서귀포현지인", title: "Sauna Regular", ratingOverall: 4, oneLineReview: "중문관광단지에서 가깝고 시설 훌륭해요.", visitedAt: "2026-01-05" },
  ],
  "jeju-3": [
    { nickname: "제주전통파", title: "Steam Veteran", ratingOverall: 4, oneLineReview: "제주 문화 테마 찜질방, 다른 곳에서 못 느끼는 감성.", visitedAt: "2026-03-02" },
    { nickname: "현무암팬", title: "Bath Explorer", ratingOverall: 5, oneLineReview: "현무암 황토방이 너무 독특하고 좋아요.", visitedAt: "2026-02-08" },
    { nickname: "제주탐구자", title: "Heat Seeker", ratingOverall: 4, oneLineReview: "용암 사우나 컨셉이 재미있어요.", visitedAt: "2025-12-31" },
  ],
  "jeju-4": [
    { nickname: "애월카페러버", title: "Sauna Regular", ratingOverall: 5, oneLineReview: "에메랄드 바다 앞 노천 스파, 꿈같은 경험.", visitedAt: "2026-03-08" },
    { nickname: "일몰사냥꾼", title: "Steam Veteran", ratingOverall: 5, oneLineReview: "일몰 타이밍에 맞춰 오면 최고의 경험.", visitedAt: "2026-02-25" },
    { nickname: "제주한달살기", title: "Heat Seeker", ratingOverall: 5, oneLineReview: "한 달 살면서 매주 왔어요. 그만큼 좋아요.", visitedAt: "2026-02-10" },
    { nickname: "노천스파매니아", title: "Bath Explorer", ratingOverall: 4, oneLineReview: "바람 많이 불면 좀 춥지만 그래도 최고.", visitedAt: "2026-01-18" },
  ],
  "jeju-5": [
    { nickname: "일출헌터", title: "Bath Explorer", ratingOverall: 5, oneLineReview: "새벽 5시 일출 보고 사우나. 진짜 인생 경험.", visitedAt: "2026-03-15" },
    { nickname: "성산여행자", title: "Sauna Regular", ratingOverall: 5, oneLineReview: "성산일출봉 배경으로 사우나 즐기는 건 여기만!", visitedAt: "2026-02-28" },
    { nickname: "새벽감성러", title: "Heat Seeker", ratingOverall: 4, oneLineReview: "새벽 사우나가 이렇게 감동적일 줄 몰랐어요.", visitedAt: "2026-02-05" },
  ],
};
